from enum import StrEnum


class ErrorCategory(StrEnum):
    VALIDATION = "VALIDATION_ERROR"
    AUTHENTICATION = "AUTHENTICATION_ERROR"
    AUTHORIZATION = "AUTHORIZATION_ERROR"
    NOT_FOUND = "RESOURCE_NOT_FOUND"
    DUPLICATE = "DUPLICATE_RESOURCE"
    DATABASE = "DATABASE_ERROR"
    INTERNAL = "INTERNAL_SERVER_ERROR"
